// ─────────────────────────────────────────────────────────────
//  PRICES: change a tier here and every scent in that tier updates.
// ─────────────────────────────────────────────────────────────
const PRICE_TIERS = {
  budget: [
    { label: "5ml", price: 6 },
    { label: "10ml", price: 10 },
  ],
  standard: [
    { label: "5ml", price: 8 },
    { label: "10ml", price: 13 },
  ],
  mid: [
    { label: "5ml", price: 10 },
    { label: "10ml", price: 17 },
  ],
  premium: [
    { label: "5ml", price: 15 },
    { label: "10ml", price: 26 },
  ],
};

// ─────────────────────────────────────────────────────────────
//  YOUR RANGE: add, remove or edit products here.
//
//  id          unique, lowercase, no spaces
//  brand       shown above the name
//  name        product name
//  family      used for the filter buttons (Fresh, Aquatic, Sweet, …)
//  vibe        one short line under the name (optional)
//  notes       main scent notes
//  sizes       a price tier from above, e.g. PRICE_TIERS.standard,
//              or your own list: [{ label: "5ml", price: 9 }, …]
//  parfumo     link to this scent on parfumo.com
//  inspiredBy  for dupes only: the original it smells like, with its Parfumo link.
//              Leave it out for designer originals.
//  inStock     set to false to show "Sold out"
//  badge       optional label on the card, e.g. "Hyped", "New", "Low stock"
//
//  Look of the bottle illustration (ignored if you set `image`):
//  color       liquid colour      capColor  cap colour
//  shape       classic | tall | round | square
//  mono        short text on the label (defaults to the brand, or its initials)
//
//  image       optional path to a real photo, e.g. "images/khamrah.jpg"
// ─────────────────────────────────────────────────────────────
window.PRODUCTS = [
  {
    id: "lattafa-khamrah",
    brand: "Lattafa",
    name: "Khamrah",
    family: "Sweet",
    vibe: "Warm, boozy and sweet. A winter favourite",
    notes: ["Cinnamon", "Dates", "Praline"],
    sizes: PRICE_TIERS.standard,
    parfumo: "https://www.parfumo.com/Perfumes/Lattafa/khamrah",
    inspiredBy: {
      brand: "Kilian",
      name: "Angels' Share",
      parfumo: "https://www.parfumo.com/Perfumes/Kilian/angels-share-eau-de-parfum",
    },
    badge: "Hyped",
    color: "#8a3b1e",
    capColor: "#c9a54e",
    shape: "round",
    inStock: true,
  },
  {
    id: "armaf-cdnim",
    brand: "Armaf",
    name: "Club de Nuit Intense Man",
    family: "Smoky & Oud",
    vibe: "Smoky pineapple. The famous Aventus dupe",
    notes: ["Lemon", "Pineapple", "Birch"],
    sizes: PRICE_TIERS.standard,
    parfumo: "https://www.parfumo.com/Perfumes/Armaf/club-de-nuit-intense-man-eau-de-toilette",
    inspiredBy: {
      brand: "Creed",
      name: "Aventus",
      parfumo: "https://www.parfumo.com/Perfumes/Creed/aventus",
    },
    badge: "Hyped",
    color: "#1f1f22",
    capColor: "#b9b9bd",
    shape: "square",
    inStock: true,
  },
  {
    id: "mm-sailing-day",
    brand: "Maison Margiela",
    name: "Replica Sailing Day",
    family: "Aquatic",
    vibe: "Clean sea breeze, easy to wear anywhere",
    notes: ["Sea notes", "Juniper", "Ambergris"],
    sizes: PRICE_TIERS.premium,
    parfumo: "https://www.parfumo.com/Perfumes/Maison_Margiela/sailing-day",
    badge: "Premium",
    color: "#8cbcd0",
    capColor: "#1b1b1d",
    shape: "tall",
    inStock: true,
  },
  {
    id: "fa-liquid-brun",
    brand: "French Avenue",
    name: "Liquid Brun",
    family: "Sweet",
    vibe: "Cinnamon and vanilla, big compliments",
    notes: ["Cinnamon", "Bourbon vanilla", "Praline"],
    sizes: PRICE_TIERS.standard,
    parfumo: "https://www.parfumo.com/Perfumes/french-avenue/liquid-brun",
    inspiredBy: {
      brand: "Parfums de Marly",
      name: "Althaïr",
      parfumo: "https://www.parfumo.com/Perfumes/Parfums_de_Marly/althair",
    },
    color: "#6b3a1f",
    capColor: "#c9a54e",
    shape: "classic",
    inStock: true,
  },
  {
    id: "lattafa-oud-for-glory",
    brand: "Lattafa",
    name: "Oud for Glory",
    family: "Smoky & Oud",
    vibe: "Dark, smoky oud for big nights",
    notes: ["Saffron", "Oud", "Patchouli"],
    sizes: PRICE_TIERS.standard,
    parfumo: "https://www.parfumo.com/Perfumes/Lattafa/oud-for-glory",
    inspiredBy: {
      brand: "Initio",
      name: "Oud for Greatness",
      parfumo: "https://www.parfumo.com/Perfumes/Initio/oud-for-greatness-eau-de-parfum",
    },
    color: "#3a2a24",
    capColor: "#c9a54e",
    shape: "square",
    inStock: true,
  },
  {
    id: "al-haramain-amber-oud-gold",
    brand: "Al Haramain",
    name: "Amber Oud Gold Edition",
    family: "Sweet",
    vibe: "Fruity, sweet and loud",
    notes: ["Bergamot", "Melon", "Vanilla"],
    sizes: PRICE_TIERS.mid,
    parfumo: "https://www.parfumo.com/Perfumes/Al_Haramain/haramain-amber-oud-gold-edition",
    inspiredBy: {
      brand: "Xerjoff",
      name: "Erba Pura",
      parfumo: "https://www.parfumo.com/Perfumes/Xerjoff/Erba_Pura",
    },
    color: "#c99a2e",
    capColor: "#8c6d1f",
    shape: "classic",
    inStock: true,
  },
  {
    id: "fa-aether-extrait",
    brand: "French Avenue",
    name: "Aether Extrait",
    family: "Fresh",
    vibe: "Crisp green apple, smart-casual",
    notes: ["Green apple", "Bergamot", "Oakmoss"],
    sizes: PRICE_TIERS.standard,
    parfumo: "https://www.parfumo.com/Perfumes/french-avenue/aether",
    inspiredBy: {
      brand: "Parfums de Marly",
      name: "Greenley",
      parfumo: "https://www.parfumo.com/Perfumes/Parfums_de_Marly/greenley",
    },
    color: "#5b8a5a",
    capColor: "#e3dccd",
    shape: "tall",
    inStock: true,
  },
  {
    id: "rasasi-hawas-ice",
    brand: "Rasasi",
    name: "Hawas Ice",
    family: "Aquatic",
    vibe: "Icy, sweet and fresh for hot days",
    notes: ["Frosted apple", "Marine notes", "Plum"],
    sizes: PRICE_TIERS.mid,
    parfumo: "https://www.parfumo.com/Perfumes/Rasasi/hawas-ice",
    inspiredBy: {
      brand: "Paco Rabanne",
      name: "Invictus Aqua",
      parfumo: "https://www.parfumo.com/Perfumes/Rabanne/Invictus_Aqua_2018",
    },
    color: "#7fc3d9",
    capColor: "#b9c4c9",
    shape: "tall",
    inStock: true,
  },
  {
    id: "fa-ravine-ginger",
    brand: "French Avenue",
    name: "Ravine Ginger",
    family: "Fresh",
    vibe: "Zesty ginger, a soft summer freshie",
    notes: ["Ginger", "Bergamot", "Vanilla"],
    sizes: PRICE_TIERS.standard,
    parfumo: "https://www.parfumo.com/Perfumes/french-avenue/ravine-ginger",
    inspiredBy: {
      brand: "Goldfield & Banks",
      name: "Ingenious Ginger",
      parfumo: "https://www.parfumo.com/Perfumes/Goldfield__Banks/ingenious-ginger",
    },
    color: "#d8a33a",
    capColor: "#2a2a2a",
    shape: "square",
    inStock: true,
  },
  {
    id: "fa-ravine-ice",
    brand: "French Avenue",
    name: "Ravine Ice",
    family: "Aquatic",
    vibe: "Salty, mossy, coastal fresh",
    notes: ["Lemon", "Sage", "Salty notes"],
    sizes: PRICE_TIERS.standard,
    parfumo: "https://www.parfumo.com/Perfumes/french-avenue/ravine-ice",
    inspiredBy: {
      brand: "Goldfield & Banks",
      name: "Pacific Rock Moss",
      parfumo: "https://www.parfumo.com/Perfumes/Goldfield__Banks/Pacific_Rock_Moss",
    },
    color: "#5f8f8a",
    capColor: "#2a2a2a",
    shape: "square",
    inStock: true,
  },
  {
    id: "versace-eros-edt",
    brand: "Versace",
    name: "Eros EDT",
    family: "Sweet",
    vibe: "Party-ready and long-lasting",
    notes: ["Mint", "Green apple", "Vanilla"],
    sizes: PRICE_TIERS.mid,
    parfumo: "https://www.parfumo.com/Perfumes/Versace/Eros_Eau_de_Toilette",
    color: "#2a8a86",
    capColor: "#c9a54e",
    shape: "tall",
    inStock: true,
  },
  {
    id: "valentino-bir-intense",
    brand: "Valentino",
    name: "Born in Roma Intense",
    family: "Sweet",
    vibe: "Smooth vanilla, big compliments",
    notes: ["Vanilla", "Lavender", "Vetiver"],
    sizes: PRICE_TIERS.premium,
    parfumo: "https://www.parfumo.com/Perfumes/Valentino/valentino-uomo-born-in-roma-intense",
    color: "#2d2645",
    capColor: "#8c7a52",
    shape: "classic",
    inStock: true,
  },
  {
    id: "jpg-le-male-edt",
    brand: "Jean Paul Gaultier",
    name: "Le Male EDT",
    family: "Sweet",
    vibe: "The lavender and vanilla classic",
    notes: ["Lavender", "Mint", "Vanilla"],
    sizes: PRICE_TIERS.mid,
    parfumo: "https://www.parfumo.com/Perfumes/Jean_Paul_Gaultier/Le_Male_Eau_de_Toilette",
    color: "#6fa3c7",
    capColor: "#b9b9bd",
    shape: "round",
    inStock: true,
  },
  {
    id: "azzaro-wanted-edt",
    brand: "Azzaro",
    name: "Wanted EDT",
    family: "Fresh",
    vibe: "Zesty lemon and ginger, easy daily wear",
    notes: ["Lemon", "Ginger", "Cardamom"],
    sizes: PRICE_TIERS.mid,
    parfumo: "https://www.parfumo.com/Perfumes/Azzaro/wanted-eau-de-toilette",
    color: "#6e747b",
    capColor: "#1b1b1d",
    shape: "round",
    inStock: true,
  },
  {
    id: "nautica-voyage",
    brand: "Nautica",
    name: "Voyage",
    family: "Aquatic",
    vibe: "Fresh and clean. A budget legend",
    notes: ["Green apple", "Lotus", "Cedar"],
    sizes: PRICE_TIERS.budget,
    parfumo: "https://www.parfumo.com/Perfumes/Nautica/Voyage_Eau_de_Toilette",
    color: "#2f5f8a",
    capColor: "#c7c7ca",
    shape: "round",
    inStock: true,
  },
  {
    id: "davidoff-cool-water",
    brand: "Davidoff",
    name: "Cool Water",
    family: "Aquatic",
    vibe: "The original fresh blue classic",
    notes: ["Mint", "Lavender", "Oakmoss"],
    sizes: PRICE_TIERS.budget,
    parfumo: "https://www.parfumo.com/Perfumes/Davidoff/Cool_Water_Eau_de_Toilette",
    color: "#2f7fb5",
    capColor: "#1e5a85",
    shape: "tall",
    inStock: true,
  },
  {
    id: "beckham-instinct",
    brand: "David Beckham",
    name: "Instinct",
    family: "Fresh",
    vibe: "Light citrus and spice, safe for school",
    notes: ["Grapefruit", "Cardamom", "Vetiver"],
    sizes: PRICE_TIERS.budget,
    parfumo: "https://www.parfumo.com/Perfumes/David_Beckham/Instinct_Eau_de_Toilette",
    color: "#b9782d",
    capColor: "#3a3a3a",
    shape: "classic",
    inStock: true,
  },
];
